services:
  backend:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue_app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
