version: "3.8"

services:
  # Backend (Laravel)
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "5173:5173" # Vite dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    networks:
      - app_network
    command: ["npm", "run", "dev"]

  # Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80" # mở phpMyAdmin ở localhost:8081
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M
    networks:
      - app_network
  # Redis
  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    networks:
      - app_network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/src:/var/www/html
    depends_on:
      - laravel
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
